# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b677ef46dc5abe4fdd1d32aa81f6de4b4eca5165eecdfa2ca5dbff231e7d92304bc703381b6d2e0c58ceaff15f2eaa8994d5ed7d57199cf70505d4021caf039

test:
  secret_key_base: c919d863348ed3ca9f7fab3e4f58ea531923771562395a594f8fb357c45b0e5d3c982c12e35e901e24958a919bfe022307095ec91d36545ac4ca4471b663d6a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
